Revert "ci: try running tests workflow on macOS x86_64 and arm64"
This reverts the previous commit.

On macOS x86_64, the workflow errored with:

    clang: error: no such file or directory: '/Users/runner/.local/c0/libs/libffi.a'

and on macOS arm64 it errored with:

    ERROR: unable to find archive matching pattern macosx_arm64.tar.xz

because the nim nightlies repo doesn't have binary builds for that platform.